language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle
before_install:
  - sudo apt-get install unzip wget -y
  - sudo mkdir lib/ && chmod a+x lib
  - cd lib 
  - sudo wget http://deps.terranetichosting.com/libs.zip
  - sudo unzip libs.zip
  - chmod a+x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew clean build -S
