dist: trusty
language: java
sudo: true
cache:
  directories:
    - $HOME/.gradle
notifications:
  email: false
jdk:
  - oraclejdk8
before_install:
  - apt-get install unzip wget -y
  - mkdir lib/ && chmod a+x lib
  - cd lib 
  - wget http://deps.terranetichosting.com/libs.zip
  - unzip libs.zip
  - chmod a+x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew clean build -S
