dist: trusty
language: java
cache:
  directories:
    - $HOME/.gradle
notifications:
  email: false
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install unzip wget -y
  - sudo mkdir lib
  - cd lib 
  - sudo wget http://deps.terranetichosting.com/libs.zip
  - sudo unzip libs.zip
  - chmod a+x gradlew && cd / ..
install: ./gradlew setupCIWorkspace -S
script: ./gradlew clean build -S
